<?xml version="1.0" encoding="utf-8"?><Database Name="Owl" Class="OwlDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=olblgislxo.database.windows.net;Initial Catalog=Owl;Persist Security Info=True;User ID=owlbat" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OwlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Venue" Member="Venues">
    <Type Name="Venue">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlaceName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SearchName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="PlaceAddresse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MyPosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Popularity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="CreatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VenuePhoto" Member="VenuePhotos">
    <Type Name="VenuePhoto">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlaceId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="VenuePhotoUrl1" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl2" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl3" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAndPost" Member="UserAndPosts">
    <Type Name="UserAndPost">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="UserProfileUrl1" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UserProfileUrl2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserProfileUrl3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Popularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenueId" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="VenueName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Time" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Sexe" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="GirlNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BoyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgeRange" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="Popularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sexe" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Popularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OutType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VenueId" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="LookingFor" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="ArrivalTime" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="GirlNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BoyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfileUrl" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="OtherInfo" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="CodeDress" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Salt" Type="System.Data.Linq.Binary" DbType="VarBinary(512) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SaltedAndHashedPassword" Type="System.Data.Linq.Binary" DbType="VarBinary(512) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetPost" Method="GetPost">
    <Parameter Name="userid" Type="System.String" DbType="VarChar(128)" />
    <ElementType Name="GetPostResult">
      <Column Name="UserId" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="UserProfileUrl1" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UserProfileUrl2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserProfileUrl3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserPopularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenueId" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="VenueName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Time" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Sexe" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="GirlNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BoyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgeRange" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PlaceAddresse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VenuePosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VenuePopularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenuePhotoUrl1" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl2" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl3" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertAnUser" Method="InsertAnUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Sexe" Parameter="sexe" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Birthday" Parameter="birthday" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertAnPost" Method="InsertAnPost">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="OutType" Parameter="outType" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="VenueId" Parameter="venueId" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LookingFor" Parameter="lookingFor" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ArrivalTime" Parameter="arrivalTime" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="GirlNumber" Parameter="girlNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="BoyNumber" Parameter="boyNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProfileUrl" Parameter="profileUrl" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="OtherInfo" Parameter="otherInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="CodeDress" Parameter="codeDress" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateAnPost" Method="UpdateAnPost">
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="OutType" Parameter="outType" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="VenueId" Parameter="venueId" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LookingFor" Parameter="lookingFor" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ArrivalTime" Parameter="arrivalTime" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="GirlNumber" Parameter="girlNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="BoyNumber" Parameter="boyNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProfileUrl" Parameter="profileUrl" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="OtherInfo" Parameter="otherInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="CodeDress" Parameter="codeDress" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetPostByUserId" Method="GetPostByUserId">
    <Parameter Name="userid" Type="System.String" DbType="VarChar(128)" />
    <ElementType Name="GetPostByUserIdResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ProfileUrl" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Popularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenueId" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="PlaceName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ArrivalTime" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Sexe" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="GirlNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BoyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OtherInfo" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="LookingFor" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="OutType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlaceAddresse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VenuePosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VenuePopularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenuePhotoUrl1" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl2" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl3" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetPosts" Method="GetPosts">
    <ElementType Name="GetPostsResult">
      <Column Name="UserId" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ProfileUrl" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UserPopularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenueId" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="PlaceName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ArrivalTime" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Sexe" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="GirlNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BoyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="OtherInfo" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CodeDress" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="OutType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LookingFor" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="PlaceAddresse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VenuePosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VenuePopularity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenuePhotoUrl1" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl2" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="VenuePhotoUrl3" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertAnMessage" Method="InsertAnMessage">
    <Parameter Name="FromUserId" Parameter="fromUserId" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="ToUserId" Parameter="toUserId" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertAnAccount" Method="InsertAnAccount">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="Salt" Parameter="salt" Type="System.Data.Linq.Binary" DbType="VarBinary(512)" />
    <Parameter Name="SaltedAndHashedPassword" Parameter="saltedAndHashedPassword" Type="System.Data.Linq.Binary" DbType="VarBinary(512)" />
    <Return Type="System.Int32" />
  </Function>
</Database>