#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlBatAzureMobileService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Owl")]
	public partial class OwlDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVenue(Venue instance);
    partial void UpdateVenue(Venue instance);
    partial void DeleteVenue(Venue instance);
    partial void InsertVenuePhoto(VenuePhoto instance);
    partial void UpdateVenuePhoto(VenuePhoto instance);
    partial void DeleteVenuePhoto(VenuePhoto instance);
    #endregion
		
		public OwlDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OwlConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Venue> Venues
		{
			get
			{
				return this.GetTable<Venue>();
			}
		}
		
		public System.Data.Linq.Table<VenuePhoto> VenuePhotos
		{
			get
			{
				return this.GetTable<VenuePhoto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venue")]
	public partial class Venue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _PlaceName;
		
		private string _SearchName;
		
		private string _PlaceAddresse;
		
		private string _MyPosition;
		
		private int _Popularity;
		
		private System.Data.Linq.Binary _Version;
		
		private System.DateTimeOffset _CreatedAt;
		
		private System.Nullable<System.DateTimeOffset> _UpdatedAt;
		
		private bool _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnPlaceNameChanging(string value);
    partial void OnPlaceNameChanged();
    partial void OnSearchNameChanging(string value);
    partial void OnSearchNameChanged();
    partial void OnPlaceAddresseChanging(string value);
    partial void OnPlaceAddresseChanged();
    partial void OnMyPositionChanging(string value);
    partial void OnMyPositionChanged();
    partial void OnPopularityChanging(int value);
    partial void OnPopularityChanged();
    partial void OnVersionChanging(System.Data.Linq.Binary value);
    partial void OnVersionChanged();
    partial void OnCreatedAtChanging(System.DateTimeOffset value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnUpdatedAtChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Venue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceName", DbType="NVarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string PlaceName
		{
			get
			{
				return this._PlaceName;
			}
			set
			{
				if ((this._PlaceName != value))
				{
					this.OnPlaceNameChanging(value);
					this.SendPropertyChanging();
					this._PlaceName = value;
					this.SendPropertyChanged("PlaceName");
					this.OnPlaceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchName", DbType="NVarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string SearchName
		{
			get
			{
				return this._SearchName;
			}
			set
			{
				if ((this._SearchName != value))
				{
					this.OnSearchNameChanging(value);
					this.SendPropertyChanging();
					this._SearchName = value;
					this.SendPropertyChanged("SearchName");
					this.OnSearchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceAddresse", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string PlaceAddresse
		{
			get
			{
				return this._PlaceAddresse;
			}
			set
			{
				if ((this._PlaceAddresse != value))
				{
					this.OnPlaceAddresseChanging(value);
					this.SendPropertyChanging();
					this._PlaceAddresse = value;
					this.SendPropertyChanged("PlaceAddresse");
					this.OnPlaceAddresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyPosition", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string MyPosition
		{
			get
			{
				return this._MyPosition;
			}
			set
			{
				if ((this._MyPosition != value))
				{
					this.OnMyPositionChanging(value);
					this.SendPropertyChanging();
					this._MyPosition = value;
					this.SendPropertyChanged("MyPosition");
					this.OnMyPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VenuePhoto")]
	public partial class VenuePhoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _PlaceId;
		
		private string _VenuePhotoUrl1;
		
		private string _VenuePhotoUrl2;
		
		private string _VenuePhotoUrl3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnPlaceIdChanging(string value);
    partial void OnPlaceIdChanged();
    partial void OnVenuePhotoUrl1Changing(string value);
    partial void OnVenuePhotoUrl1Changed();
    partial void OnVenuePhotoUrl2Changing(string value);
    partial void OnVenuePhotoUrl2Changed();
    partial void OnVenuePhotoUrl3Changing(string value);
    partial void OnVenuePhotoUrl3Changed();
    #endregion
		
		public VenuePhoto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceId", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PlaceId
		{
			get
			{
				return this._PlaceId;
			}
			set
			{
				if ((this._PlaceId != value))
				{
					this.OnPlaceIdChanging(value);
					this.SendPropertyChanging();
					this._PlaceId = value;
					this.SendPropertyChanged("PlaceId");
					this.OnPlaceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl1", DbType="NVarChar(160)")]
		public string VenuePhotoUrl1
		{
			get
			{
				return this._VenuePhotoUrl1;
			}
			set
			{
				if ((this._VenuePhotoUrl1 != value))
				{
					this.OnVenuePhotoUrl1Changing(value);
					this.SendPropertyChanging();
					this._VenuePhotoUrl1 = value;
					this.SendPropertyChanged("VenuePhotoUrl1");
					this.OnVenuePhotoUrl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl2", DbType="NVarChar(160)")]
		public string VenuePhotoUrl2
		{
			get
			{
				return this._VenuePhotoUrl2;
			}
			set
			{
				if ((this._VenuePhotoUrl2 != value))
				{
					this.OnVenuePhotoUrl2Changing(value);
					this.SendPropertyChanging();
					this._VenuePhotoUrl2 = value;
					this.SendPropertyChanged("VenuePhotoUrl2");
					this.OnVenuePhotoUrl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl3", DbType="NVarChar(160)")]
		public string VenuePhotoUrl3
		{
			get
			{
				return this._VenuePhotoUrl3;
			}
			set
			{
				if ((this._VenuePhotoUrl3 != value))
				{
					this.OnVenuePhotoUrl3Changing(value);
					this.SendPropertyChanging();
					this._VenuePhotoUrl3 = value;
					this.SendPropertyChanged("VenuePhotoUrl3");
					this.OnVenuePhotoUrl3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
