#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlBatAzureMobileService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Owl")]
	public partial class OwlDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVenue(Venue instance);
    partial void UpdateVenue(Venue instance);
    partial void DeleteVenue(Venue instance);
    partial void InsertVenuePhoto(VenuePhoto instance);
    partial void UpdateVenuePhoto(VenuePhoto instance);
    partial void DeleteVenuePhoto(VenuePhoto instance);
    partial void InsertUserAndPost(UserAndPost instance);
    partial void UpdateUserAndPost(UserAndPost instance);
    partial void DeleteUserAndPost(UserAndPost instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertPost(Post instance);
    partial void UpdatePost(Post instance);
    partial void DeletePost(Post instance);
    #endregion
		
		public OwlDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OwlConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OwlDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Venue> Venues
		{
			get
			{
				return this.GetTable<Venue>();
			}
		}
		
		public System.Data.Linq.Table<VenuePhoto> VenuePhotos
		{
			get
			{
				return this.GetTable<VenuePhoto>();
			}
		}
		
		public System.Data.Linq.Table<UserAndPost> UserAndPosts
		{
			get
			{
				return this.GetTable<UserAndPost>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Post> Posts
		{
			get
			{
				return this.GetTable<Post>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPosts")]
		public ISingleResult<GetPostsResult> GetPosts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdateAs", DbType="DateTimeOffset")] System.Nullable<System.DateTimeOffset> updateAs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), updateAs);
			return ((ISingleResult<GetPostsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPost")]
		public ISingleResult<GetPostResult> GetPost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((ISingleResult<GetPostResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertAnUser")]
		public int InsertAnUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="NVarChar(MAX)")] string userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sexe", DbType="NVarChar(MAX)")] string sexe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Birthday", DbType="NVarChar(MAX)")] string birthday)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, userName, sexe, birthday);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertAnPost")]
		public int InsertAnPost([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="NVarChar(MAX)")] string userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OutType", DbType="NVarChar(MAX)")] string outType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VenueId", DbType="NVarChar(MAX)")] string venueId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LookingFor", DbType="NVarChar(MAX)")] string lookingFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArrivalTime", DbType="NVarChar(MAX)")] string arrivalTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GirlNumber", DbType="Int")] System.Nullable<int> girlNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BoyNumber", DbType="Int")] System.Nullable<int> boyNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfileUrl", DbType="NVarChar(MAX)")] string profileUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OtherInfo", DbType="NVarChar(MAX)")] string otherInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeDress", DbType="NVarChar(MAX)")] string codeDress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, outType, venueId, lookingFor, arrivalTime, girlNumber, boyNumber, profileUrl, otherInfo, codeDress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateAnPost")]
		public int UpdateAnPost([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="NVarChar(MAX)")] string userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OutType", DbType="NVarChar(MAX)")] string outType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VenueId", DbType="NVarChar(MAX)")] string venueId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LookingFor", DbType="NVarChar(MAX)")] string lookingFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArrivalTime", DbType="NVarChar(MAX)")] string arrivalTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GirlNumber", DbType="Int")] System.Nullable<int> girlNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BoyNumber", DbType="Int")] System.Nullable<int> boyNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfileUrl", DbType="NVarChar(MAX)")] string profileUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OtherInfo", DbType="NVarChar(MAX)")] string otherInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeDress", DbType="NVarChar(MAX)")] string codeDress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, outType, venueId, lookingFor, arrivalTime, girlNumber, boyNumber, profileUrl, otherInfo, codeDress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPostByUserId")]
		public ISingleResult<GetPostByUserIdResult> GetPostByUserId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((ISingleResult<GetPostByUserIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venue")]
	public partial class Venue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _PlaceName;
		
		private string _SearchName;
		
		private string _PlaceAddresse;
		
		private string _MyPosition;
		
		private int _Popularity;
		
		private System.Data.Linq.Binary _Version;
		
		private System.DateTimeOffset _CreatedAt;
		
		private System.Nullable<System.DateTimeOffset> _UpdatedAt;
		
		private bool _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnPlaceNameChanging(string value);
    partial void OnPlaceNameChanged();
    partial void OnSearchNameChanging(string value);
    partial void OnSearchNameChanged();
    partial void OnPlaceAddresseChanging(string value);
    partial void OnPlaceAddresseChanged();
    partial void OnMyPositionChanging(string value);
    partial void OnMyPositionChanged();
    partial void OnPopularityChanging(int value);
    partial void OnPopularityChanged();
    partial void OnVersionChanging(System.Data.Linq.Binary value);
    partial void OnVersionChanged();
    partial void OnCreatedAtChanging(System.DateTimeOffset value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnUpdatedAtChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Venue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceName", DbType="NVarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string PlaceName
		{
			get
			{
				return this._PlaceName;
			}
			set
			{
				if ((this._PlaceName != value))
				{
					this.OnPlaceNameChanging(value);
					this.SendPropertyChanging();
					this._PlaceName = value;
					this.SendPropertyChanged("PlaceName");
					this.OnPlaceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchName", DbType="NVarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string SearchName
		{
			get
			{
				return this._SearchName;
			}
			set
			{
				if ((this._SearchName != value))
				{
					this.OnSearchNameChanging(value);
					this.SendPropertyChanging();
					this._SearchName = value;
					this.SendPropertyChanged("SearchName");
					this.OnSearchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceAddresse", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string PlaceAddresse
		{
			get
			{
				return this._PlaceAddresse;
			}
			set
			{
				if ((this._PlaceAddresse != value))
				{
					this.OnPlaceAddresseChanging(value);
					this.SendPropertyChanging();
					this._PlaceAddresse = value;
					this.SendPropertyChanged("PlaceAddresse");
					this.OnPlaceAddresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyPosition", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string MyPosition
		{
			get
			{
				return this._MyPosition;
			}
			set
			{
				if ((this._MyPosition != value))
				{
					this.OnMyPositionChanging(value);
					this.SendPropertyChanging();
					this._MyPosition = value;
					this.SendPropertyChanged("MyPosition");
					this.OnMyPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VenuePhoto")]
	public partial class VenuePhoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _PlaceId;
		
		private string _VenuePhotoUrl1;
		
		private string _VenuePhotoUrl2;
		
		private string _VenuePhotoUrl3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnPlaceIdChanging(string value);
    partial void OnPlaceIdChanged();
    partial void OnVenuePhotoUrl1Changing(string value);
    partial void OnVenuePhotoUrl1Changed();
    partial void OnVenuePhotoUrl2Changing(string value);
    partial void OnVenuePhotoUrl2Changed();
    partial void OnVenuePhotoUrl3Changing(string value);
    partial void OnVenuePhotoUrl3Changed();
    #endregion
		
		public VenuePhoto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceId", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PlaceId
		{
			get
			{
				return this._PlaceId;
			}
			set
			{
				if ((this._PlaceId != value))
				{
					this.OnPlaceIdChanging(value);
					this.SendPropertyChanging();
					this._PlaceId = value;
					this.SendPropertyChanged("PlaceId");
					this.OnPlaceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl1", DbType="NVarChar(160)")]
		public string VenuePhotoUrl1
		{
			get
			{
				return this._VenuePhotoUrl1;
			}
			set
			{
				if ((this._VenuePhotoUrl1 != value))
				{
					this.OnVenuePhotoUrl1Changing(value);
					this.SendPropertyChanging();
					this._VenuePhotoUrl1 = value;
					this.SendPropertyChanged("VenuePhotoUrl1");
					this.OnVenuePhotoUrl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl2", DbType="NVarChar(160)")]
		public string VenuePhotoUrl2
		{
			get
			{
				return this._VenuePhotoUrl2;
			}
			set
			{
				if ((this._VenuePhotoUrl2 != value))
				{
					this.OnVenuePhotoUrl2Changing(value);
					this.SendPropertyChanging();
					this._VenuePhotoUrl2 = value;
					this.SendPropertyChanged("VenuePhotoUrl2");
					this.OnVenuePhotoUrl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl3", DbType="NVarChar(160)")]
		public string VenuePhotoUrl3
		{
			get
			{
				return this._VenuePhotoUrl3;
			}
			set
			{
				if ((this._VenuePhotoUrl3 != value))
				{
					this.OnVenuePhotoUrl3Changing(value);
					this.SendPropertyChanging();
					this._VenuePhotoUrl3 = value;
					this.SendPropertyChanged("VenuePhotoUrl3");
					this.OnVenuePhotoUrl3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAndPost")]
	public partial class UserAndPost : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _UserId;
		
		private string _UserName;
		
		private string _UserProfileUrl1;
		
		private string _UserProfileUrl2;
		
		private string _UserProfileUrl3;
		
		private System.Nullable<int> _Popularity;
		
		private string _VenueId;
		
		private string _VenueName;
		
		private string _Time;
		
		private string _Sexe;
		
		private System.Nullable<int> _GirlNumber;
		
		private System.Nullable<int> _BoyNumber;
		
		private string _AgeRange;
		
		private string _Description;
		
		private System.DateTimeOffset _UpdateAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserProfileUrl1Changing(string value);
    partial void OnUserProfileUrl1Changed();
    partial void OnUserProfileUrl2Changing(string value);
    partial void OnUserProfileUrl2Changed();
    partial void OnUserProfileUrl3Changing(string value);
    partial void OnUserProfileUrl3Changed();
    partial void OnPopularityChanging(System.Nullable<int> value);
    partial void OnPopularityChanged();
    partial void OnVenueIdChanging(string value);
    partial void OnVenueIdChanged();
    partial void OnVenueNameChanging(string value);
    partial void OnVenueNameChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnGirlNumberChanging(System.Nullable<int> value);
    partial void OnGirlNumberChanged();
    partial void OnBoyNumberChanging(System.Nullable<int> value);
    partial void OnBoyNumberChanged();
    partial void OnAgeRangeChanging(string value);
    partial void OnAgeRangeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUpdateAtChanging(System.DateTimeOffset value);
    partial void OnUpdateAtChanged();
    #endregion
		
		public UserAndPost()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(160) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl1", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string UserProfileUrl1
		{
			get
			{
				return this._UserProfileUrl1;
			}
			set
			{
				if ((this._UserProfileUrl1 != value))
				{
					this.OnUserProfileUrl1Changing(value);
					this.SendPropertyChanging();
					this._UserProfileUrl1 = value;
					this.SendPropertyChanged("UserProfileUrl1");
					this.OnUserProfileUrl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl2", DbType="NVarChar(200)")]
		public string UserProfileUrl2
		{
			get
			{
				return this._UserProfileUrl2;
			}
			set
			{
				if ((this._UserProfileUrl2 != value))
				{
					this.OnUserProfileUrl2Changing(value);
					this.SendPropertyChanging();
					this._UserProfileUrl2 = value;
					this.SendPropertyChanged("UserProfileUrl2");
					this.OnUserProfileUrl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl3", DbType="NVarChar(200)")]
		public string UserProfileUrl3
		{
			get
			{
				return this._UserProfileUrl3;
			}
			set
			{
				if ((this._UserProfileUrl3 != value))
				{
					this.OnUserProfileUrl3Changing(value);
					this.SendPropertyChanging();
					this._UserProfileUrl3 = value;
					this.SendPropertyChanged("UserProfileUrl3");
					this.OnUserProfileUrl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="Int")]
		public System.Nullable<int> Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueId", DbType="VarChar(128)")]
		public string VenueId
		{
			get
			{
				return this._VenueId;
			}
			set
			{
				if ((this._VenueId != value))
				{
					this.OnVenueIdChanging(value);
					this.SendPropertyChanging();
					this._VenueId = value;
					this.SendPropertyChanged("VenueId");
					this.OnVenueIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueName", DbType="VarChar(128)")]
		public string VenueName
		{
			get
			{
				return this._VenueName;
			}
			set
			{
				if ((this._VenueName != value))
				{
					this.OnVenueNameChanging(value);
					this.SendPropertyChanging();
					this._VenueName = value;
					this.SendPropertyChanged("VenueName");
					this.OnVenueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(8)")]
		public string Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(8)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirlNumber", DbType="Int")]
		public System.Nullable<int> GirlNumber
		{
			get
			{
				return this._GirlNumber;
			}
			set
			{
				if ((this._GirlNumber != value))
				{
					this.OnGirlNumberChanging(value);
					this.SendPropertyChanging();
					this._GirlNumber = value;
					this.SendPropertyChanged("GirlNumber");
					this.OnGirlNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoyNumber", DbType="Int")]
		public System.Nullable<int> BoyNumber
		{
			get
			{
				return this._BoyNumber;
			}
			set
			{
				if ((this._BoyNumber != value))
				{
					this.OnBoyNumberChanging(value);
					this.SendPropertyChanging();
					this._BoyNumber = value;
					this.SendPropertyChanged("BoyNumber");
					this.OnBoyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeRange", DbType="VarChar(64)")]
		public string AgeRange
		{
			get
			{
				return this._AgeRange;
			}
			set
			{
				if ((this._AgeRange != value))
				{
					this.OnAgeRangeChanging(value);
					this.SendPropertyChanging();
					this._AgeRange = value;
					this.SendPropertyChanged("AgeRange");
					this.OnAgeRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateAt", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset UpdateAt
		{
			get
			{
				return this._UpdateAt;
			}
			set
			{
				if ((this._UpdateAt != value))
				{
					this.OnUpdateAtChanging(value);
					this.SendPropertyChanging();
					this._UpdateAt = value;
					this.SendPropertyChanged("UpdateAt");
					this.OnUpdateAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _UserId;
		
		private string _UserName;
		
		private System.Nullable<int> _Popularity;
		
		private string _Sexe;
		
		private System.DateTimeOffset _CreatedAt;
		
		private System.DateTimeOffset _UpdatedAt;
		
		private string _Birthday;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPopularityChanging(System.Nullable<int> value);
    partial void OnPopularityChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnCreatedAtChanging(System.DateTimeOffset value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.DateTimeOffset value);
    partial void OnUpdatedAtChanged();
    partial void OnBirthdayChanging(string value);
    partial void OnBirthdayChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(160) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="Int")]
		public System.Nullable<int> Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(8)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="VarChar(10)")]
		public string Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Post")]
	public partial class Post : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _UserId;
		
		private System.Nullable<int> _Popularity;
		
		private string _OutType;
		
		private string _VenueId;
		
		private string _LookingFor;
		
		private string _ArrivalTime;
		
		private System.Nullable<int> _GirlNumber;
		
		private System.Nullable<int> _BoyNumber;
		
		private string _ProfileUrl;
		
		private string _OtherInfo;
		
		private System.DateTimeOffset _UpdateAt;
		
		private string _CodeDress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnPopularityChanging(System.Nullable<int> value);
    partial void OnPopularityChanged();
    partial void OnOutTypeChanging(string value);
    partial void OnOutTypeChanged();
    partial void OnVenueIdChanging(string value);
    partial void OnVenueIdChanged();
    partial void OnLookingForChanging(string value);
    partial void OnLookingForChanged();
    partial void OnArrivalTimeChanging(string value);
    partial void OnArrivalTimeChanged();
    partial void OnGirlNumberChanging(System.Nullable<int> value);
    partial void OnGirlNumberChanged();
    partial void OnBoyNumberChanging(System.Nullable<int> value);
    partial void OnBoyNumberChanged();
    partial void OnProfileUrlChanging(string value);
    partial void OnProfileUrlChanged();
    partial void OnOtherInfoChanging(string value);
    partial void OnOtherInfoChanged();
    partial void OnUpdateAtChanging(System.DateTimeOffset value);
    partial void OnUpdateAtChanged();
    partial void OnCodeDressChanging(string value);
    partial void OnCodeDressChanged();
    #endregion
		
		public Post()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="Int")]
		public System.Nullable<int> Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutType", DbType="VarChar(50)")]
		public string OutType
		{
			get
			{
				return this._OutType;
			}
			set
			{
				if ((this._OutType != value))
				{
					this.OnOutTypeChanging(value);
					this.SendPropertyChanging();
					this._OutType = value;
					this.SendPropertyChanged("OutType");
					this.OnOutTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueId", DbType="VarChar(128)")]
		public string VenueId
		{
			get
			{
				return this._VenueId;
			}
			set
			{
				if ((this._VenueId != value))
				{
					this.OnVenueIdChanging(value);
					this.SendPropertyChanging();
					this._VenueId = value;
					this.SendPropertyChanged("VenueId");
					this.OnVenueIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LookingFor", DbType="VarChar(128)")]
		public string LookingFor
		{
			get
			{
				return this._LookingFor;
			}
			set
			{
				if ((this._LookingFor != value))
				{
					this.OnLookingForChanging(value);
					this.SendPropertyChanging();
					this._LookingFor = value;
					this.SendPropertyChanged("LookingFor");
					this.OnLookingForChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArrivalTime", DbType="VarChar(8)")]
		public string ArrivalTime
		{
			get
			{
				return this._ArrivalTime;
			}
			set
			{
				if ((this._ArrivalTime != value))
				{
					this.OnArrivalTimeChanging(value);
					this.SendPropertyChanging();
					this._ArrivalTime = value;
					this.SendPropertyChanged("ArrivalTime");
					this.OnArrivalTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirlNumber", DbType="Int")]
		public System.Nullable<int> GirlNumber
		{
			get
			{
				return this._GirlNumber;
			}
			set
			{
				if ((this._GirlNumber != value))
				{
					this.OnGirlNumberChanging(value);
					this.SendPropertyChanging();
					this._GirlNumber = value;
					this.SendPropertyChanged("GirlNumber");
					this.OnGirlNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoyNumber", DbType="Int")]
		public System.Nullable<int> BoyNumber
		{
			get
			{
				return this._BoyNumber;
			}
			set
			{
				if ((this._BoyNumber != value))
				{
					this.OnBoyNumberChanging(value);
					this.SendPropertyChanging();
					this._BoyNumber = value;
					this.SendPropertyChanged("BoyNumber");
					this.OnBoyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileUrl", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string ProfileUrl
		{
			get
			{
				return this._ProfileUrl;
			}
			set
			{
				if ((this._ProfileUrl != value))
				{
					this.OnProfileUrlChanging(value);
					this.SendPropertyChanging();
					this._ProfileUrl = value;
					this.SendPropertyChanged("ProfileUrl");
					this.OnProfileUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherInfo", DbType="VarChar(250)")]
		public string OtherInfo
		{
			get
			{
				return this._OtherInfo;
			}
			set
			{
				if ((this._OtherInfo != value))
				{
					this.OnOtherInfoChanging(value);
					this.SendPropertyChanging();
					this._OtherInfo = value;
					this.SendPropertyChanged("OtherInfo");
					this.OnOtherInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateAt", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset UpdateAt
		{
			get
			{
				return this._UpdateAt;
			}
			set
			{
				if ((this._UpdateAt != value))
				{
					this.OnUpdateAtChanging(value);
					this.SendPropertyChanging();
					this._UpdateAt = value;
					this.SendPropertyChanged("UpdateAt");
					this.OnUpdateAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeDress", DbType="VarChar(64)")]
		public string CodeDress
		{
			get
			{
				return this._CodeDress;
			}
			set
			{
				if ((this._CodeDress != value))
				{
					this.OnCodeDressChanging(value);
					this.SendPropertyChanging();
					this._CodeDress = value;
					this.SendPropertyChanged("CodeDress");
					this.OnCodeDressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetPostsResult
	{
		
		private string _UserId;
		
		private string _UserName;
		
		private string _UserProfileUrl1;
		
		private string _UserProfileUrl2;
		
		private string _UserProfileUrl3;
		
		private System.Nullable<int> _UserPopularity;
		
		private string _VenueId;
		
		private string _VenueName;
		
		private string _Time;
		
		private string _Sexe;
		
		private System.Nullable<int> _GirlNumber;
		
		private System.Nullable<int> _BoyNumber;
		
		private string _AgeRange;
		
		private string _Description;
		
		private string _PlaceAddresse;
		
		private string _VenuePosition;
		
		private System.Nullable<int> _VenuePopularity;
		
		private string _VenuePhotoUrl1;
		
		private string _VenuePhotoUrl2;
		
		private string _VenuePhotoUrl3;
		
		public GetPostsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(160) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl1", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string UserProfileUrl1
		{
			get
			{
				return this._UserProfileUrl1;
			}
			set
			{
				if ((this._UserProfileUrl1 != value))
				{
					this._UserProfileUrl1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl2", DbType="NVarChar(200)")]
		public string UserProfileUrl2
		{
			get
			{
				return this._UserProfileUrl2;
			}
			set
			{
				if ((this._UserProfileUrl2 != value))
				{
					this._UserProfileUrl2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl3", DbType="NVarChar(200)")]
		public string UserProfileUrl3
		{
			get
			{
				return this._UserProfileUrl3;
			}
			set
			{
				if ((this._UserProfileUrl3 != value))
				{
					this._UserProfileUrl3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPopularity", DbType="Int")]
		public System.Nullable<int> UserPopularity
		{
			get
			{
				return this._UserPopularity;
			}
			set
			{
				if ((this._UserPopularity != value))
				{
					this._UserPopularity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueId", DbType="VarChar(128)")]
		public string VenueId
		{
			get
			{
				return this._VenueId;
			}
			set
			{
				if ((this._VenueId != value))
				{
					this._VenueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueName", DbType="VarChar(128)")]
		public string VenueName
		{
			get
			{
				return this._VenueName;
			}
			set
			{
				if ((this._VenueName != value))
				{
					this._VenueName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(8)")]
		public string Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this._Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(8)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this._Sexe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirlNumber", DbType="Int")]
		public System.Nullable<int> GirlNumber
		{
			get
			{
				return this._GirlNumber;
			}
			set
			{
				if ((this._GirlNumber != value))
				{
					this._GirlNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoyNumber", DbType="Int")]
		public System.Nullable<int> BoyNumber
		{
			get
			{
				return this._BoyNumber;
			}
			set
			{
				if ((this._BoyNumber != value))
				{
					this._BoyNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeRange", DbType="VarChar(64)")]
		public string AgeRange
		{
			get
			{
				return this._AgeRange;
			}
			set
			{
				if ((this._AgeRange != value))
				{
					this._AgeRange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceAddresse", DbType="NVarChar(200)")]
		public string PlaceAddresse
		{
			get
			{
				return this._PlaceAddresse;
			}
			set
			{
				if ((this._PlaceAddresse != value))
				{
					this._PlaceAddresse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePosition", DbType="NVarChar(50)")]
		public string VenuePosition
		{
			get
			{
				return this._VenuePosition;
			}
			set
			{
				if ((this._VenuePosition != value))
				{
					this._VenuePosition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePopularity", DbType="Int")]
		public System.Nullable<int> VenuePopularity
		{
			get
			{
				return this._VenuePopularity;
			}
			set
			{
				if ((this._VenuePopularity != value))
				{
					this._VenuePopularity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl1", DbType="NVarChar(160)")]
		public string VenuePhotoUrl1
		{
			get
			{
				return this._VenuePhotoUrl1;
			}
			set
			{
				if ((this._VenuePhotoUrl1 != value))
				{
					this._VenuePhotoUrl1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl2", DbType="NVarChar(160)")]
		public string VenuePhotoUrl2
		{
			get
			{
				return this._VenuePhotoUrl2;
			}
			set
			{
				if ((this._VenuePhotoUrl2 != value))
				{
					this._VenuePhotoUrl2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl3", DbType="NVarChar(160)")]
		public string VenuePhotoUrl3
		{
			get
			{
				return this._VenuePhotoUrl3;
			}
			set
			{
				if ((this._VenuePhotoUrl3 != value))
				{
					this._VenuePhotoUrl3 = value;
				}
			}
		}
	}
	
	public partial class GetPostResult
	{
		
		private string _UserId;
		
		private string _UserName;
		
		private string _UserProfileUrl1;
		
		private string _UserProfileUrl2;
		
		private string _UserProfileUrl3;
		
		private System.Nullable<int> _UserPopularity;
		
		private string _VenueId;
		
		private string _VenueName;
		
		private string _Time;
		
		private string _Sexe;
		
		private System.Nullable<int> _GirlNumber;
		
		private System.Nullable<int> _BoyNumber;
		
		private string _AgeRange;
		
		private string _Description;
		
		private string _PlaceAddresse;
		
		private string _VenuePosition;
		
		private System.Nullable<int> _VenuePopularity;
		
		private string _VenuePhotoUrl1;
		
		private string _VenuePhotoUrl2;
		
		private string _VenuePhotoUrl3;
		
		public GetPostResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(160) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl1", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string UserProfileUrl1
		{
			get
			{
				return this._UserProfileUrl1;
			}
			set
			{
				if ((this._UserProfileUrl1 != value))
				{
					this._UserProfileUrl1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl2", DbType="NVarChar(200)")]
		public string UserProfileUrl2
		{
			get
			{
				return this._UserProfileUrl2;
			}
			set
			{
				if ((this._UserProfileUrl2 != value))
				{
					this._UserProfileUrl2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserProfileUrl3", DbType="NVarChar(200)")]
		public string UserProfileUrl3
		{
			get
			{
				return this._UserProfileUrl3;
			}
			set
			{
				if ((this._UserProfileUrl3 != value))
				{
					this._UserProfileUrl3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPopularity", DbType="Int")]
		public System.Nullable<int> UserPopularity
		{
			get
			{
				return this._UserPopularity;
			}
			set
			{
				if ((this._UserPopularity != value))
				{
					this._UserPopularity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueId", DbType="VarChar(128)")]
		public string VenueId
		{
			get
			{
				return this._VenueId;
			}
			set
			{
				if ((this._VenueId != value))
				{
					this._VenueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueName", DbType="VarChar(128)")]
		public string VenueName
		{
			get
			{
				return this._VenueName;
			}
			set
			{
				if ((this._VenueName != value))
				{
					this._VenueName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(8)")]
		public string Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this._Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(8)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this._Sexe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirlNumber", DbType="Int")]
		public System.Nullable<int> GirlNumber
		{
			get
			{
				return this._GirlNumber;
			}
			set
			{
				if ((this._GirlNumber != value))
				{
					this._GirlNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoyNumber", DbType="Int")]
		public System.Nullable<int> BoyNumber
		{
			get
			{
				return this._BoyNumber;
			}
			set
			{
				if ((this._BoyNumber != value))
				{
					this._BoyNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeRange", DbType="VarChar(64)")]
		public string AgeRange
		{
			get
			{
				return this._AgeRange;
			}
			set
			{
				if ((this._AgeRange != value))
				{
					this._AgeRange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceAddresse", DbType="NVarChar(200)")]
		public string PlaceAddresse
		{
			get
			{
				return this._PlaceAddresse;
			}
			set
			{
				if ((this._PlaceAddresse != value))
				{
					this._PlaceAddresse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePosition", DbType="NVarChar(50)")]
		public string VenuePosition
		{
			get
			{
				return this._VenuePosition;
			}
			set
			{
				if ((this._VenuePosition != value))
				{
					this._VenuePosition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePopularity", DbType="Int")]
		public System.Nullable<int> VenuePopularity
		{
			get
			{
				return this._VenuePopularity;
			}
			set
			{
				if ((this._VenuePopularity != value))
				{
					this._VenuePopularity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl1", DbType="NVarChar(160)")]
		public string VenuePhotoUrl1
		{
			get
			{
				return this._VenuePhotoUrl1;
			}
			set
			{
				if ((this._VenuePhotoUrl1 != value))
				{
					this._VenuePhotoUrl1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl2", DbType="NVarChar(160)")]
		public string VenuePhotoUrl2
		{
			get
			{
				return this._VenuePhotoUrl2;
			}
			set
			{
				if ((this._VenuePhotoUrl2 != value))
				{
					this._VenuePhotoUrl2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl3", DbType="NVarChar(160)")]
		public string VenuePhotoUrl3
		{
			get
			{
				return this._VenuePhotoUrl3;
			}
			set
			{
				if ((this._VenuePhotoUrl3 != value))
				{
					this._VenuePhotoUrl3 = value;
				}
			}
		}
	}
	
	public partial class GetPostByUserIdResult
	{
		
		private string _Id;
		
		private string _UserId;
		
		private string _UserName;
		
		private string _ProfileUrl;
		
		private System.Nullable<int> _Popularity;
		
		private string _VenueId;
		
		private string _PlaceName;
		
		private string _ArrivalTime;
		
		private string _Sexe;
		
		private System.Nullable<int> _GirlNumber;
		
		private System.Nullable<int> _BoyNumber;
		
		private string _OtherInfo;
		
		private string _LookingFor;
		
		private string _OutType;
		
		private string _PlaceAddresse;
		
		private string _VenuePosition;
		
		private System.Nullable<int> _VenuePopularity;
		
		private string _VenuePhotoUrl1;
		
		private string _VenuePhotoUrl2;
		
		private string _VenuePhotoUrl3;
		
		public GetPostByUserIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(160)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileUrl", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string ProfileUrl
		{
			get
			{
				return this._ProfileUrl;
			}
			set
			{
				if ((this._ProfileUrl != value))
				{
					this._ProfileUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="Int")]
		public System.Nullable<int> Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this._Popularity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenueId", DbType="VarChar(128)")]
		public string VenueId
		{
			get
			{
				return this._VenueId;
			}
			set
			{
				if ((this._VenueId != value))
				{
					this._VenueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceName", DbType="NVarChar(80)")]
		public string PlaceName
		{
			get
			{
				return this._PlaceName;
			}
			set
			{
				if ((this._PlaceName != value))
				{
					this._PlaceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArrivalTime", DbType="VarChar(32)")]
		public string ArrivalTime
		{
			get
			{
				return this._ArrivalTime;
			}
			set
			{
				if ((this._ArrivalTime != value))
				{
					this._ArrivalTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(8)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this._Sexe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirlNumber", DbType="Int")]
		public System.Nullable<int> GirlNumber
		{
			get
			{
				return this._GirlNumber;
			}
			set
			{
				if ((this._GirlNumber != value))
				{
					this._GirlNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoyNumber", DbType="Int")]
		public System.Nullable<int> BoyNumber
		{
			get
			{
				return this._BoyNumber;
			}
			set
			{
				if ((this._BoyNumber != value))
				{
					this._BoyNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherInfo", DbType="VarChar(250)")]
		public string OtherInfo
		{
			get
			{
				return this._OtherInfo;
			}
			set
			{
				if ((this._OtherInfo != value))
				{
					this._OtherInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LookingFor", DbType="VarChar(128)")]
		public string LookingFor
		{
			get
			{
				return this._LookingFor;
			}
			set
			{
				if ((this._LookingFor != value))
				{
					this._LookingFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutType", DbType="VarChar(50)")]
		public string OutType
		{
			get
			{
				return this._OutType;
			}
			set
			{
				if ((this._OutType != value))
				{
					this._OutType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceAddresse", DbType="NVarChar(200)")]
		public string PlaceAddresse
		{
			get
			{
				return this._PlaceAddresse;
			}
			set
			{
				if ((this._PlaceAddresse != value))
				{
					this._PlaceAddresse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePosition", DbType="NVarChar(50)")]
		public string VenuePosition
		{
			get
			{
				return this._VenuePosition;
			}
			set
			{
				if ((this._VenuePosition != value))
				{
					this._VenuePosition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePopularity", DbType="Int")]
		public System.Nullable<int> VenuePopularity
		{
			get
			{
				return this._VenuePopularity;
			}
			set
			{
				if ((this._VenuePopularity != value))
				{
					this._VenuePopularity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl1", DbType="NVarChar(160)")]
		public string VenuePhotoUrl1
		{
			get
			{
				return this._VenuePhotoUrl1;
			}
			set
			{
				if ((this._VenuePhotoUrl1 != value))
				{
					this._VenuePhotoUrl1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl2", DbType="NVarChar(160)")]
		public string VenuePhotoUrl2
		{
			get
			{
				return this._VenuePhotoUrl2;
			}
			set
			{
				if ((this._VenuePhotoUrl2 != value))
				{
					this._VenuePhotoUrl2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenuePhotoUrl3", DbType="NVarChar(160)")]
		public string VenuePhotoUrl3
		{
			get
			{
				return this._VenuePhotoUrl3;
			}
			set
			{
				if ((this._VenuePhotoUrl3 != value))
				{
					this._VenuePhotoUrl3 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
